### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Guuours** [wwmoraes/pvpgn-server-docker#1]
I pulled your image from docker hub and started it, every seems all good.
I can see the instance running with ps commmand

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                NAMES
b08464f54a8b        wwmoraes/pvpgn-server:latest   "/usr/local/pvpgn/sb…"   55 minutes ago      Up 55 minutes       4000/tcp, 6112/tcp   magical_snyder

but I can't connect with my d2 client, I'm using d2 lod 1.13d without any mod, is it the right version I should use?

**Comment by wwmoraes** [comment]
Sorry for the late reply! From the pasted output I see you didn't publish the ports to the host, i.e. `-p 4000:4000 -p 6112:6112`.

The full command to run would be then `docker run -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server`.

**Comment by wwmoraes** [comment]
I've added those port publish flags on the `run` make target, so newcomers or anyone just passing by and testing will get a more straightforward result out of it. Thank you for the feedback 🥇
