### ISSUE TITLE
doesnt work..

### ISSUE THREAD

**Issue by SiDChik** [wwmoraes/pvpgn-server-docker#2]
stops after start with exit code 0
```
 docker run -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server
```

**Comment by wwmoraes** [comment]
What's the output? If I run this exact command I get a `You are currently running PvPGN 1.99.7.2.1-PRO`, it blocks the terminal and works as expected.

[![asciicast](https://asciinema.org/a/3HXo3EeOKDUwQHIYb082oidoM.svg)](https://asciinema.org/a/3HXo3EeOKDUwQHIYb082oidoM)

**Comment by PalasX** [comment]
i also get no output, no blocking, nada with "docker run -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server"
same with "docker run -it -v $PWD/etc:/usr/local/pvpgn/etc -v $PWD/var:/usr/local/pvpgn/var -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server" after making config changes.

i had the error where, when running image to copy var and etc files to host volume, got access denied. solved by running as --user 1000:1000
So i tried running and forcing user 1000, but no change. still no output, exits back to terminal.

**Comment by wwmoraes** [comment]
@PalasX you need to add `-t/--tty` to get a TTY, otherwise you won't get output indeed.

Use `docker run -it -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server /usr/local/pvpgn/sbin/bnetd -f -D` to get some debugging info from bnetd to debug your config if needed.

As for your permission problem, that was expected, as this is how docker bind volumes work. You "fixed" with `--user 1000:1000` as that's probably the UID and GID of your user on the host system (you can check by running `id -u` and `id -g`).

**Comment by PalasX** [comment]
![image](https://user-images.githubusercontent.com/37154966/164952512-f4cdbf05-bada-4209-9d20-20f166bffbf0.png)
1000 is the userid and groupid of my user, yes. and sorry, i was typing the command with "-it", but forgot to add it. I get zero output.

Adding -D for debug info, i also get no output to console.  portainer reports no logs matching any filter at all, "No log line matching the '' filter"

**Comment by PalasX** [comment]
owner@e6520b:/home/owner/docker/pvpgn2$ docker events&
[1] 1115694
owner@e6520b:/home/owner/docker/pvpgn2$ docker run -v $PWD/etc:/usr/local/pvpgn/etc -v $PWD/var:/usr/local/pvpgn/var -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server
2022-04-25T16:27:39.773419181Z container create 222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab (image=wwmoraes/pvpgn-server, name=focused_bouman)
2022-04-25T16:27:39.774946917Z container attach 222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab (image=wwmoraes/pvpgn-server, name=focused_bouman)
2022-04-25T16:27:39.822423847Z network connect 7c78fb484bb77b8431b6384be8dd3bea5e53830be4bc103f884584c1350b2f14 (container=222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab, name=bridge, type=bridge)
2022-04-25T16:27:40.209658569Z container start 222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab (image=wwmoraes/pvpgn-server, name=focused_bouman)
2022-04-25T16:27:40.490094063Z container die 222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab (exitCode=132, image=wwmoraes/pvpgn-server, name=focused_bouman)
2022-04-25T16:27:40.724131815Z network disconnect 7c78fb484bb77b8431b6384be8dd3bea5e53830be4bc103f884584c1350b2f14 (container=222fe64ba114229aa541d4bbaaf79264784576e61d48961adb908efa0bd020ab, name=bridge, type=bridge)
owner@e6520b:~/docker/pvpgn2$ fg
docker events
^C
owner@e6520b:/home/owner/docker/pvpgn2$

![image](https://user-images.githubusercontent.com/37154966/165132661-f74c9afd-ad3a-40e0-8c87-34cb576d7f31.png)

**Comment by PalasX** [comment]
this should have nothing to do with being on Ubuntu Server, right? i understand you develop on MacOS?

**Comment by PalasX** [comment]
![image](https://user-images.githubusercontent.com/37154966/165140410-6d34286a-9799-4758-af3b-7fe89b0747cf.png)

owner@e6520b:~/docker/pvpgn2$ docker run -it -p 4000:4000 -p 6112:6112 wwmoraes/pvpgn-server /bin/sh
/ $ ls
bin    dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ $ cd /usr/local/pvpgn/
~ $ ls
bin    etc    sbin   share  var
~ $ cd sbin
~/sbin $ ls
bnetd     bntrackd  d2cs      d2dbs
~/sbin $ ./bnetd
Illegal instruction (core dumped)
~/sbin $ ./bnetd -f -D
Illegal instruction (core dumped)
~/sbin $

**Comment by PalasX** [comment]
![image](https://user-images.githubusercontent.com/37154966/165157253-ed760c66-73c1-4658-b281-286346524c7a.png)
same in latest plain image:

owner@e6520b:/home/owner/docker/pvpgn2$ docker run -it -p 4000:4000 -p 6112:6112 --entrypoint /bin/sh wwmoraes/pvpgn-server:1.99.7.2.1-plain
/ $ cd sbin
/sbin $ ./bnetd
Illegal instruction (core dumped)
/sbin $ exit
owner@e6520b:/home/owner/docker/pvpgn2$

**Comment by PalasX** [comment]
![image](https://user-images.githubusercontent.com/37154966/165162938-aef0d720-46dd-4939-a045-94cffc4f792a.png)

Working on arm7. Looks like there is an issue with your AMD64 build not targetting the right architecture?

**Comment by wwmoraes** [comment]
Thanks @PalasX for the troubleshooting and logs!

> this should have nothing to do with being on Ubuntu Server, right? i understand you develop on MacOS?

I do, but that's irrelevant. As a matter of fact, I tested this container on intel x64, armv8 (aarch64) and armlv7l devices running linuxes, all working just fine.

<img width="583" alt="Screenshot 2022-04-26 at 00 07 09" src="https://user-images.githubusercontent.com/682095/165182997-43e0bf48-1de8-498a-821a-a3da4c0fa25e.png">

Are you running on an AMD or Intel CPU? A quick search about containers with exit code 132 points towards a lack of support for specific instruction sets, such as AVX or SSE2. This also adds up to the _illegal instruction_ error message you see when running the binary directly. You might find those links useful for further troubleshooting:

- https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132
- https://hub.mender.io/t/unable-to-start-on-premise-demo-server-per-getting-started-instructions/1414/23

If you have the relevant isntruction sets for your CPU then we'll need to reach out to the upstream pvpgn team for further investigation.

**Comment by PalasX** [comment]
Intel cpu, 2720qm, so probably missing AVX op codes.my apologies, i thought
your image built from source to target arch, didn't realise this was an
upstream error.

I went ahead and put it on a raspberry pi 4, and it works perfectly. Just
had to load a "dummy" image first so i could docker cp image:/var/pvpgn
/localdir, the usr/local paths in documentation aren't used, so the copy
out entry point failed  a quick chown 1001:1001 to the local var and etc,
bind mount, and its working like a champ.

Thanks again!

**Comment by wwmoraes** [comment]
> i thought your image built from source to target arch

It is. The Dockerfile is designed to be built on BuildKit, which supports cross-architecture builds. Aside from that, I use the upstream build instructions, and I don't disable anything in particular.

This means gcc will use by default all the target architecture extensions supported by the [reported/chosen processor family](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html).

> the usr/local paths in documentation aren't used

I've reworked the image recently, so if you're using any of the new tags then indeed the paths have changed. I dropped the installation prefix to make path less redundant and easier to use. You can find out which volume paths are expected for the image version you are using by inspecting it:

```sh
docker image inspect -f '{{range $key, $value := .Config.Volumes}}{{println $key}}{{end}}' ww
moraes/pvpgn-server:<tag>
```

This should yield:

- `/usr/local/pvpgn/etc` and `/usr/local/pvpgn/var` for legacy tags like `latest`
- `/etc/pvpgn` and `/var/pvpgn` for the new style tags such as `latest-mysql`

>  so i could docker cp image:/var/pvpgn /localdir, the usr/local paths in documentation aren't used, so the copy out entry point failed

Check the updated README, I've added some instructions on how to copy those files out more easily 😉

**Comment by PalasX** [comment]
Awesome! You're continued efforts make it crazy easy for folks to enjoy some true gems of older games. Thank you <3
