### ISSUE TITLE
incorrectly on the DSM6.23

### ISSUE THREAD

**Issue by 4nolove** [wwmoraes/pvpgn-server-docker#6]
This image runs incorrectly on the DSM6.23 system with no logs, but it runs very well on Centos，thx

**Comment by wwmoraes** [comment]
@4nolove the container does not change in any way how the PVPGN server logs. In other words, PVPGN sends its messages both to the stdout and stderr. I'm not familiar with the DSM6.23 to say what it does with those descriptors. Check the upstream for more info on how to adjust your logging mechanism or troubleshoot it.

https://kb.synology.com/en-us/DSM/tutorial/How_can_I_debug_and_fix_common_Docker_container_issues
https://www.reddit.com/r/synology/comments/hvoyb9/docker_shows_no_containers_images_etc_after_dsm/
